import React, { useEffect } from "react";
import { FileText, AlertTriangle, UserCheck, Ban, Scale } from "lucide-react";
import "./TermsOfService.css";

const TermsOfService = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="terms-wrapper">
      <div className="terms-container">
        <header className="terms-header">
          <div className="terms-badge">
            <FileText size={16} />
            <span>Legal Agreement</span>
          </div>
          <h1>Terms of Service</h1>
          <p>Effective Date: April 2026</p>
        </header>

        <section className="terms-section">
          <div className="terms-title">
            <AlertTriangle size={22} color="#f59e0b" />
            <h2>Medical Disclaimer</h2>
          </div>
          <p>
            MedInsightAI provides information generated by artificial
            intelligence. This information is for{" "}
            <strong>educational and informational purposes only</strong>. It is
            NOT medical advice. Always seek the advice of a physician or other
            qualified health provider with any questions you may have regarding
            a medical condition.
          </p>
        </section>

        <section className="terms-section">
          <div className="terms-title">
            <UserCheck size={22} color="#3b82f6" />
            <h2>User Accounts</h2>
          </div>
          <p>
            To access certain features like medical history, you must create an
            account. You are responsible for maintaining the confidentiality of
            your account credentials. You agree to notify us immediately of any
            unauthorized use of your account.
          </p>
        </section>

        <section className="terms-section">
          <div className="terms-title">
            <Ban size={22} color="#ef4444" />
            <h2>Prohibited Use</h2>
          </div>
          <p>
            You agree not to use MedInsightAI for any unlawful purposes or to
            conduct any activity that would violate the rights of others. This
            includes attempting to reverse engineer the AI models or using the
            platform to distribute misleading medical information.
          </p>
        </section>

        <section className="terms-section">
          <div className="terms-title">
            <Scale size={22} color="#6366f1" />
            <h2>Limitation of Liability</h2>
          </div>
          <p>
            MedInsightAI and its developers shall not be held liable for any
            direct, indirect, or incidental damages resulting from the use or
            inability to use the service. The use of AI-generated insights is
            strictly at your own risk.
          </p>
        </section>

        <footer className="terms-footer">
          <p>
            By using MedInsightAI, you acknowledge that you have read and agreed
            to these Terms of Service.
          </p>
        </footer>
      </div>
    </div>
  );
};

export default TermsOfService;
